title: Turtles Site
author: Turtle #4
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Turtles live in the sewer and eat pizza. It's a site about that.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
